сделал остальное + тесты
Vyacheslav-TKI/Kindergarden pull request #3
Opened 2024-11-21 22:44 UTC by Vyacheslav-TKI

2024-11-22 12:17 UTC, MarinaPaley requested changes

2024-11-22 12:17 UTC, MarinaPaley commented on Solver/Group.h
> +		std::vector<std::unique_ptr<Baby>> babies;
`std::shared...`

2024-11-22 12:17 UTC, MarinaPaley commented on Solver/Group.h
> +		Teacher* get_teacher() const;
Лучше копированием

2024-11-22 12:17 UTC, MarinaPaley commented on Solver/Group.cpp
> +			if (baby->gender == '�') {
проблема кодировки

2024-11-22 12:17 UTC, MarinaPaley commented on Solver/Group.cpp
> +		}
https://[cplusplus.com/reference/algorithm/find_if/](https://cplusplus.com/reference/algorithm/find_if/)

2024-11-22 12:17 UTC, MarinaPaley commented on Solver/Schedule.h
> +		void set_schedule(const std::string& day, const std::string& inputed_group_name, const std::vector<std::string>& activities);
inputed_group_name -> Group* (или умный)

2024-11-29 12:57 UTC, MarinaPaley requested changes
Не нашла связей в другую сторону (от другого класса).
Проверьте, не течет ли память

2024-11-29 12:57 UTC, MarinaPaley commented on Solver/Group.h
> +		std::vector<std::shared_ptr<Baby>> babies;
Скорее всего вектор сырых указателей. Группа (чисто теоретически) может быть пустой

2024-11-29 12:57 UTC, MarinaPaley commented on Solver/Group.cpp
> +		babies.push_back(child);
и в обратную сторону. ребенок имеет ссылку на группу

2024-11-29 12:57 UTC, MarinaPaley commented on Solver/Schedule.cpp
> +		if (!group) {
`const std::shared_ptr<Group>&` для такого типа это как?

2024-11-29 12:57 UTC, MarinaPaley commented on Solver/Schedule.h
> +		std::map<std::string, std::vector<std::string>> group_schedule;
очень неудобно пользоваться такой структурой
Я бы сделала group, day, activity - это одна строка в расписании. Проверка на валидность каждой строки - не задача этого класса (не может быть дня, больше 5, у одной группы в это время только одна активность и т.д)

2024-12-06 15:43 UTC, MarinaPaley requested changes
Расписание - это одна строка (Группа, Активность, день, время). Но. Создаете через shared_ptr<Schedule> с параметрами только день и время, а потом добавляете (одтельные функции) группу и активность

2024-12-06 15:43 UTC, MarinaPaley commented on Solver/Baby.h
> +		std::weak_ptr<Group> group;
`shared_ptr`

2024-12-06 15:43 UTC, MarinaPaley commented on Solver/Group.h
> +		std::vector<std::shared_ptr<Baby>> babies;
`std::vector<Baby*> babies; `

2024-12-13 13:43 UTC, MarinaPaley requested changes
1. Внимательно смотрим что класс shared от себя
2. Прячем конструктор
3. Делаем статический метод create у каждого класса
4. "\n"
5. char - gender

2024-12-17 11:44 UTC, MarinaPaley requested changes

2024-12-17 11:44 UTC, MarinaPaley commented on Kindergarden/main.cpp
> +        Schedule schedule;
Вот не должно этого быть! Запретите конструктор. Разрешайте создавать объект ТОЛЬКО через указатель

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Group.cpp
> +        if (!educator) {
Что за С!
!educator 
:imp:

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Group.cpp
> +        if (!educator) {
:imp:

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Group.cpp
> +        if (!child) {
:imp:

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Group.cpp
> +    Group::~Group() = default;
Да зачем Вам деструктор вообще?

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Group.h
> +        ~Group();
не нужен

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Group.h
> +    class Group : public std::enable_shared_from_this<Group>
final

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Schedule.cpp
> +
https://github.com/MarinaPaley/LibraryCpp/blob/master/Library/Author.cpp#L16
![photo_2024-12-17_14-38-23](https://github.com/user-attachments/assets/d4194597-b2eb-41e9-bca1-c3193b133249)
https://en.cppreference.com/w/cpp/chrono/operator%22%22h

Можно пользоваться ВСЕМ!!! а не изобретать велосипед

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Schedule.cpp
> +            if (entry) {
когда это может быть?

2024-12-17 11:44 UTC, MarinaPaley commented on Solver/Schedule.cpp
> +    Schedule::~Schedule() = default;
я не понимаю, что не понимаете Вы(

2024-12-17 11:44 UTC, MarinaPaley commented on SolverTests/BabyTests.cpp
> +            std::string fio = "���� �������";
Файл должен быть сохранен в кодировке `UTF-8`

2024-12-17 11:44 UTC, MarinaPaley commented on SolverTests/BabyTests.cpp
> +    };
Нужно проверить, что ребенка можно добавить в группу и удалить из нее

2024-12-17 19:00 UTC, Vyacheslav-TKI commented on Solver/Group.cpp
> +        if (!educator) {
я не понял вопроса насчет данных условий

2024-12-18 13:37 UTC, MarinaPaley requested changes

2024-12-18 13:37 UTC, MarinaPaley commented on Solver/Schedule.cpp
> +            throw std::invalid_argument("�������� ������ �������. ��������� HH:MM");
Файл должен быть сохранен в кодировке `UTF-8`

2024-12-18 13:37 UTC, MarinaPaley commented on Solver/Schedule.cpp
> +        entry->group = group;
`group = shared_from_this();`

2024-12-18 13:37 UTC, MarinaPaley commented on Solver/Schedule.h
> +    class Schedule {
final, enabled_shared...

2024-12-18 13:37 UTC, MarinaPaley commented on Solver/Group.h
> +        static std::shared_ptr<Group> create(const std::string& name, Teacher* educator);
`static std::shared_ptr<Group> create(const std::string& name);`

2024-12-18 13:37 UTC, MarinaPaley commented on Solver/Group.h
> +
`void add_teacher(const std::weak_ptr<Teacher>& teacher);`

2024-12-18 16:01 UTC, MarinaPaley approved these changes

2024-12-18 19:00 UTC, merged